# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "MBNFnQAzU5c1GV958KZE7deGTbdEGSce6pFUbXWvgYQ1vf+TlGEjcr+ASbW6qzmfQq9p3r161tOkgvildsuLwwq4Yf2HQTooWkEAlgb6dcgR0sf+0Iv5aoLoYvZmYpe97jCizUHk9grnduZC6BBQtGp4aKJXujgz1dqM3xuWkWM4PRv2pMlTEnWuEwATs4ud68Z41f5vE0RKqbib59kgj/kMFz5R2CirEmzvagbtZQj1bF+pwP4Q3kSKyUI1rzMTWps4bHh/ZC50lbaxcjhYZKO/0ZFUTIt8eOJ17AUU2Ohrq5p3dUFMW7olw5kQzgGBqZdCCET5Ho9fJz28HHFGizIgvCXCcG9RlEN+N3xcqk3LVbpQ+lrUAAPYRQi1oELccnuT9E00WdWa6vQ3Ao2H5VDN/DhJFWQuoNMYcGsxyR4XoDKl7j1UW9Ie3apJKw30jtxXkvwN0gbmi6Fw+e4M02Bx58rhumHlKqEdDHcjsbmMp5H/wGdf1VJGTIxFVHxbuAwL8Pdh812nG0vWojfVcXmKwEshHtizt/BCp/6lmgNNWVDo/FvNW7ePBNgYfv1DJ+uxPNS5pcdmH21kQeU9KrlyMLd+cTmKiQzd0wOLWunLAFZrkxZ8oV2Ndnx20seV10fsvbP7CXrt+Tndmb5GD1/KP9K5yEBMVBmbF9Z2AQ8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
