travis:
  secure:
    BINSTAR_TOKEN: jiYN+MmgdcwKsliFQZcabeMId8R84iIXYyj8Fv98w4hLDm1teA/6/B/qEXrKyZk98pcIqYoYtlnHikud6ZW+H14VPZHL/kEhP0L7Ce4pCi6yZlrtNJrnsUQVigJW4J58serRcPnQTcnxE8uz7c3xJlrnNXsNyjXRYeqE3tLBdH0GuYSqUbPEJHCNB5XXnxHV+3ec/9KalJuvTxapgU4zeHzml36MbPhiOJOdQGNHhJwrIuh2QdnJN47wPBqySjGQCxo5W2QIXDvdngW4t923jLNAarYZy8teulDNFf3TRmZoX29Bjf+peRvjRyxAN/Zu4k4IDKPsbpks+E/esnRJ9a30zJ6RIjKU5QjEeGRWemtWWvIe4syxa4hl8JE1bzoyoBiQ2JZ6zbtcE9JDb4zgusKHxMx46IICC0ttgJZkG5iWe+gAl0OkNk4PSk2dAp0pc20Ins19vERyynRLqjZK8k7MRQ0vecH12a0iRs/JU9vYvNLdi5+HmQDstLl2gqpI7IyMAVHeHxztAu4NuU0DokbLea5u6/90JDGs+i1IkLmW/fDGf+4Czasev/4u2HAPd+eH2p30mmNN79K7CDU09baMFm9zkWFAJ4z1YeoY7H66OkR3UjUH2q9/vv+09WO+f9msazA3ieQCJ5g1pIQJKYU1F7g3p404fncDIyti+po=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
